# Generated by Django 4.2.7 on 2025-03-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='economicevent',
            old_name='country',
            new_name='company',
        ),
    ]
